'use strict';
const $=id=>document.getElementById(id), headers=['اسم الصنف','كود الصنف','كمية الجرد الفعلي1','كمية الجرد الفعلي2'];
let db=null,user=null,active=null,items=[],page=0,editing=null,busy=false,demo=false;
const size=40,fmt=n=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:6}).format(n),escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const digits=s=>String(s??'').replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[۰-۹]/g,c=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)).replace(/٫/g,'.');
function quantity(v){const s=digits(v).trim();if(!s)return null;if(!/^\d+(\.\d{1,6})?$/.test(s)||!Number.isFinite(Number(s))||Number(s)>1e12)throw Error('أدخل كمية موجبة أو صفرًا، حتى ٦ منازل عشرية.');return Number(s)}
const complete=i=>i.count1!==null&&i.count2!==null;
function notice(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('toast').hidden=true,4500)}
function show(id){$(id).showModal()}
function errorText(e){if(!navigator.onLine)return 'لا يوجد اتصال بالإنترنت. لم يتم الحفظ؛ أبقِ النافذة مفتوحة وأعد المحاولة.';if(/schema cache|does not exist|Could not find/i.test(e.message))return 'قاعدة البيانات غير مهيأة. نفّذ ملف setup.sql من إعدادات الاتصال في SQL Editor داخل Supabase.';if(/Invalid login/i.test(e.message))return 'البريد الإلكتروني أو كلمة المرور غير صحيحة.';return e.message||'تعذر إكمال العملية. أعد المحاولة.'}
function requireUser(){if(!db){show('settingsDialog');return false}if(!user){show('authDialog');return false}return true}
function filtered(){const q=digits($('search').value).trim().toLocaleLowerCase(),mode=$('searchMode').value,f=$('filter').value;return items.filter(i=>{const hay=mode==='code'?i.code:mode==='name'?i.name:i.code+' '+i.name;return digits(hay).toLocaleLowerCase().includes(q)&&(f==='all'||f==='pending'&&!complete(i)||f==='done'&&complete(i)||f==='diff'&&complete(i)&&i.count1!==i.count2)})}
function render(){const n=items.length,c=items.filter(complete).length; $('total').textContent=fmt(n);$('counted').textContent=fmt(c);$('pending').textContent=fmt(n-c);$('percent').textContent=fmt(n?Math.round(c/n*100):0)+'٪';$('bar').style.width=(n?c/n*100:0)+'%';$('sessionTitle').textContent=active?.name||'قائمة الأصناف';$('sessionMeta').textContent=active?(demo?'نموذج تجريبي — لا يُحفظ بعد إغلاق الصفحة': 'محفوظ في Supabase · '+new Date(active.created_at).toLocaleDateString('ar-SA')):'ابدأ برفع ملف Excel لإنشاء جلسة جرد';$('exportBtn').disabled=!n;const list=filtered();page=Math.max(0,Math.min(page,Math.ceil(list.length/size)-1));$('rows').innerHTML=list.slice(page*size,(page+1)*size).map((i,k)=>`<tr><td>${fmt(page*size+k+1)}</td><td>${escapeHTML(i.name)}</td><td>${escapeHTML(i.code)}</td><td>${i.count1===null?'—':fmt(i.count1)}</td><td>${i.count2===null?'—':fmt(i.count2)}</td><td><span class="badge ${complete(i)?i.count1===i.count2?'done':'diff':''}">${complete(i)?i.count1===i.count2?'مكتمل':'اختلاف الكميات':'بانتظار الإكمال'}</span></td><td><button class="row-edit" data-edit="${i.id}">إدخال الكمية</button></td></tr>`).join('');$('empty').hidden=n>0;$('resultCount').textContent=n?`${fmt(list.length)} صنف من ${fmt(n)}`:'لا توجد أصناف بعد';if(n&&!list.length)$('rows').innerHTML='<tr><td colspan="7" style="text-align:center;padding:45px">لا توجد أصناف مطابقة للبحث أو التصفية.</td></tr>';$('prev').disabled=page===0;$('next').disabled=(page+1)*size>=list.length;$('pageLabel').textContent=fmt(page+1)}
function connection(){ $('connection').textContent=user?'متصل · Supabase':'بانتظار تسجيل الدخول';$('setupNotice').hidden=!!user;$('accountBtn').querySelector('span').textContent=user?'تسجيل الخروج':'تسجيل الدخول';}
async function initClient(cfg){if(!window.supabase)throw Error('تعذر تحميل مكتبة الاتصال. تحقق من الإنترنت وأعد تحميل الصفحة.');db=window.supabase.createClient(cfg.url,cfg.key);const {data,error}=await db.auth.getSession();if(error)throw error;user=data.session?.user||null;db.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;connection()});connection()}
function edit(id){editing=items.find(i=>i.id===id);if(!editing)return;$('editName').textContent=editing.name;$('editCode').textContent=editing.code;$('q1').value=editing.count1??'';$('q2').value=editing.count2??'';$('editError').textContent='';show('editDialog');$('q1').focus()}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!busy)$(b.dataset.close).close()});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>{if(busy)e.preventDefault()}));
$('rows').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)edit(b.dataset.edit)};
['search','filter','searchMode'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{page=0;render()}));
$('search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const result=filtered(),exact=result.filter(i=>digits(i.code).toLowerCase()===digits($('search').value).trim().toLowerCase());if(exact.length===1)edit(exact[0].id);else if(result.length===1)edit(result[0].id);else notice('اختر الصنف المطلوب من نتائج البحث.')}};
$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};$('currentNav').onclick=()=>$('search').focus();
$('editForm').onsubmit=async e=>{e.preventDefault();if(busy)return;$('editError').textContent='';try{const count1=quantity($('q1').value),count2=quantity($('q2').value);busy=true;$('saveBtn').disabled=true;$('saveBtn').textContent='جارٍ الحفظ…';if(!demo){if(!user)throw Error('انتهت جلسة الدخول. أغلق هذه النافذة وسجّل الدخول مجددًا.');const {data,error}=await db.from('inventory_items').update({count1,count2}).eq('id',editing.id).eq('session_id',active.id).select('id').single();if(error)throw error;if(!data)throw Error('لم يتم حفظ الكمية. أعد المحاولة.')}Object.assign(editing,{count1,count2});render();$('editDialog').close();notice(demo?'تم تحديث النموذج التجريبي فقط':'تم حفظ كمية الجرد');$('search').focus();$('search').select()}catch(err){$('editError').textContent=errorText(err)}finally{busy=false;$('saveBtn').disabled=false;$('saveBtn').textContent='حفظ الكمية'}};
function openImport(){if(!requireUser())return;$('importError').textContent='';$('importName').value='جرد '+new Date().toLocaleDateString('ar-SA');show('importDialog')}
$('newBtn').onclick=openImport;$('uploadEmpty').onclick=openImport;
function workbook(){if(!window.XLSX)throw Error('تعذر تحميل أداة Excel. تحقق من الإنترنت وأعد تحميل الصفحة.');return window.XLSX}
function readSheet(buffer){const X=workbook(),book=X.read(buffer,{type:'array'}),sheet=book.Sheets[book.SheetNames[0]];if(!sheet||!sheet['!ref'])throw Error('الورقة الأولى فارغة.');const range=X.utils.decode_range(sheet['!ref']);if(range.e.r-range.s.r>20000||range.e.c-range.s.c>3)throw Error('استخدم أربعة أعمدة فقط، وبحد أقصى ٢٠٬٠٠٠ صف.');const rows=X.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false,blankrows:false});const norm=s=>String(s).replace(/[\s_]/g,'');if(rows[0]?.length!==4||!headers.every((h,i)=>norm(rows[0][i])===norm(h)))throw Error('عناوين الأعمدة غير مطابقة. نزّل قالب Excel واستخدم ترتيب الأعمدة الموجود فيه.');const parsed=rows.slice(1).filter(r=>r.some(v=>String(v).trim())).map((r,k)=>{const name=String(r[0]??'').trim(),code=String(r[1]??'').trim();if(!name||!code)throw Error(`الصف ${k+2}: اسم الصنف وكوده مطلوبان.`);if(name.length>500||code.length>200)throw Error(`الصف ${k+2}: الاسم أو الكود طويل جدًا.`);try{return{name,code,count1:quantity(String(r[2]??'').replace(/,/g,'')),count2:quantity(String(r[3]??'').replace(/,/g,'')),position:k}}catch(err){throw Error(`الصف ${k+2}: ${err.message}`)}});if(!parsed.length)throw Error('لا توجد أصناف في الملف.');return parsed}
$('importForm').onsubmit=async e=>{e.preventDefault();if(busy)return;try{if(!user)throw Error('سجّل الدخول أولًا.');const file=$('file').files[0];if(!file||! /\.(xlsx|xls)$/i.test(file.name))throw Error('اختر ملف Excel بصيغة xlsx أو xls.');if(file.size>10*1024*1024)throw Error('حجم الملف يتجاوز ١٠ ميجابايت.');busy=true;$('importSubmit').disabled=true;$('importSubmit').textContent='جارٍ الاستيراد والحفظ…';$('importError').textContent='';const parsed=readSheet(await file.arrayBuffer());const {data,error}=await db.rpc('create_inventory_session',{session_name:$('importName').value.trim(),source_file:file.name,item_rows:parsed});if(error)throw error;await loadSession(data);$('importDialog').close();$('file').value='';notice('تم استيراد '+fmt(parsed.length)+' صنف وحفظ جلسة الجرد')}catch(err){$('importError').textContent=errorText(err)}finally{busy=false;$('importSubmit').disabled=false;$('importSubmit').textContent='استيراد وبدء الجرد'}};
async function loadSession(id){const {data:s,error}=await db.from('inventory_sessions').select('*').eq('id',id).single();if(error)throw error;const loaded=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('inventory_items').select('*').eq('session_id',id).order('position').order('id').range(offset,offset+999);if(error)throw error;loaded.push(...data);if(data.length<1000)break}active=s;items=loaded;demo=false;page=0;$('search').value='';$('filter').value='all';render()}
$('historyBtn').onclick=async()=>{if(!requireUser())return;show('historyDialog');$('historyList').textContent='جارٍ تحميل الجلسات…';try{const all=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('inventory_sessions').select('*').order('created_at',{ascending:false}).order('id').range(offset,offset+999);if(error)throw error;all.push(...data);if(data.length<1000)break}$('historyList').innerHTML=all.length?all.map(s=>`<button class="history-item" data-session="${s.id}">${escapeHTML(s.name)}<small>${new Date(s.created_at).toLocaleString('ar-SA')} · ${escapeHTML(s.source_file)}</small></button>`).join(''):'لا توجد جلسات محفوظة بعد.'}catch(err){$('historyList').textContent=errorText(err)}};
$('historyList').onclick=async e=>{const b=e.target.closest('[data-session]');if(!b||busy)return;busy=true;b.disabled=true;try{await loadSession(b.dataset.session);$('historyDialog').close();notice('تم فتح جلسة الجرد')}catch(err){notice(errorText(err))}finally{busy=false;b.disabled=false}};
function downloadExcel(rows,name){const X=workbook(),sheet=X.utils.aoa_to_sheet([headers,...rows]);sheet['!cols']=[{wch:38},{wch:23},{wch:25},{wch:25}];const book=X.utils.book_new();X.utils.book_append_sheet(book,sheet,'الجرد');book.Workbook={Views:[{RTL:true}]};X.writeFile(book,name)}
$('templateBtn').onclick=()=>{try{downloadExcel([],'قالب-جرد.xlsx')}catch(e){notice(errorText(e))}};
$('exportBtn').onclick=()=>{try{downloadExcel(items.map(i=>[i.name,i.code,i.count1,i.count2]),(active.name.replace(/[\\/:*?"<>|]/g,'-'))+'.xlsx');notice('تم تصدير جميع أصناف الجلسة')}catch(e){notice(errorText(e))}};
$('demoBtn').onclick=()=>{demo=true;active={name:'جرد المستودع الرئيسي — نموذج',created_at:new Date().toISOString()};items=[['ورق تصوير A4 — ٥٠٠ ورقة','001024',120,120],['قلم حبر أزرق','001025',85,null],['ملف حفظ مستندات','001026',40,38],['دباسة مكتبية معدنية','001027',null,null],['شريط تغليف شفاف','001028',0,0],['دفتر ملاحظات A5','001029',null,null]].map(([name,code,count1,count2],position)=>({id:crypto.randomUUID(),name,code,count1,count2,position}));render()};
$('settingsBtn').onclick=$('connectBtn').onclick=()=>show('settingsDialog');
$('settingsForm').onsubmit=async e=>{e.preventDefault();try{const url=new URL($('projectUrl').value.trim()),key=$('publicKey').value.trim();if(url.protocol!=='https:'||!url.hostname.endsWith('.supabase.co'))throw Error('أدخل رابط مشروع Supabase الصحيح بصيغة HTTPS.');if(key.startsWith('sb_secret_'))throw Error('هذا مفتاح سري. استخدم Publishable أو anon فقط.');if(key.startsWith('eyJ')){try{const p=JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(p.role!=='anon')throw Error('استخدم مفتاح anon فقط.')}catch{throw Error('مفتاح anon غير صالح أو ليس عامًا.')}}else if(!key.startsWith('sb_publishable_'))throw Error('أدخل مفتاح Publishable أو anon صحيحًا.');const cfg={url:url.origin,key};await initClient(cfg);localStorage.setItem('jard-connection',JSON.stringify(cfg));items=[];active=null;demo=false;render();$('settingsDialog').close();notice('تم ضبط الاتصال؛ سجّل الدخول للبدء')}catch(err){$('settingsError').textContent=errorText(err)}};
$('accountBtn').onclick=async()=>{if(!db){show('settingsDialog');return}if(user){const {error}=await db.auth.signOut();if(error){notice(errorText(error));return}user=null;items=[];active=null;demo=false;render();connection();notice('تم تسجيل الخروج')}else show('authDialog')};
$('authForm').onsubmit=async e=>{e.preventDefault();$('loginBtn').disabled=true;$('authError').textContent='';try{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;user=data.user;$('password').value='';connection();$('authDialog').close();notice('تم تسجيل الدخول. يمكنك رفع الملف أو فتح سجل الجرد.')}catch(err){$('authError').textContent=errorText(err)}finally{$('loginBtn').disabled=false}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_inventory',description:'Search the current inventory session by item name or code.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(typeof input?.query!=='string')throw Error('query must be a string');$('search').value=input.query;page=0;render();return{total:filtered().length,items:filtered().slice(0,40).map(({name,code,count1,count2})=>({name,code,count1,count2}))}}})).catch(()=>{})}catch{}}
render();(async()=>{try{let cfg=window.JARD_CONFIG;try{cfg=JSON.parse(localStorage.getItem('jard-connection'))||cfg}catch{}if(cfg){$('projectUrl').value=cfg.url;$('publicKey').value=cfg.key;await initClient(cfg)}}catch(e){notice(errorText(e))}})();
